### ISSUE TITLE
FR: Maschine Jam Support

### ISSUE THREAD

**Issue by cyanit** [git-moss/DrivenByMoss#108]
Hello!
Driven by moss is pretty awesome so far. What I'm (personally) missing, is a modded Maschine Jam Script. Its a really awesome, portable controller, but Native instruments and Bitwig are not willing to update the (pretty old) script that's written for v1.3.6. 

Idk if you have one, but if you do you probably know that some of the core features (like the browser knob) are not implemented yet. Is there any chance we'll see it be driven by moss? Would be awesome :)

Have a nice one!

**Comment by git-moss** [comment]
I don't have a Maschine Jam but I can try to get my hands on one.

**Comment by MINDoSOFT** [comment]
Hello there and happy new year !

Your work with DrivenByMoss is very exciting !

I have a Maschine JAM and I am trying to develop a plugin for it using your code.

Have some questions though. Are you using the OpenJDK or the OracleJDK and also which version of it are you using ?

Currently I am using https://github.com/marctdt/Bitwig_MaschineJam to control the Maschine JAM but I am worried because it uses the old v1 API of bitwig, and I believe it deserves a rewrite in Java using your code. This repository has a controller editor template which I think I can reuse to get it up and running with your code.

Do you have like a guide, to get someone up and running with developing in DrivenByMoss, I mean like which files I need to adjust in order to get the Maschine JAM working with it. I thought a good start would be to start with implementing the Scene and Clip launching.

Thank you for your time !

**Comment by MINDoSOFT** [comment]
Having a couple of build errors. Do you know how to fix them ?

```
Description	Resource	Path	Location	Type
'<>' cannot be used with anonymous classes	MaschineMikroMk3ControllerSetup.java	/DrivenByMoss/src/main/java/de/mossgrabers/controller/maschine/mikro/mk3	line 286	Java Problem
```

```
Description	Resource	Path	Location	Type
The method getDefinedPackage(String) is undefined for the type ClassLoader	AbstractControllerExtensionDefinition.java	/DrivenByMoss/src/main/java/de/mossgrabers/bitwig/framework/extension	line 64	Java Problem
```

Also I had to change the JDK used in the build path. From JDK 12 to JDK 1.8 because its the one you mention in your video https://www.youtube.com/watch?v=jSiF7tmkLHE&list=PLqRWeSPiYQ66KBGONBenPv1O3luQCFQR2&index=9 Maybe that is causing the problems ?

**Comment by git-moss** [comment]
Bitwig 3.1 (API 10) requires the use of JDK 12. I use the version from AdoptOpenJDK:
https://adoptopenjdk.net/releases.html?variant=openjdk12&jvmVariant=hotspot

**Comment by MINDoSOFT** [comment]
Great thanks !

**Comment by cyanit** [comment]
@MINDoSOFT the resource is for the Maschine Mikro Mk3, are you now mapping the jam or micro?
Just out of interest :)

**Comment by MINDoSOFT** [comment]
Hi there ! 
I have the Maschine JAM so that is what I'll try to map.
But it'll take quite some time, as I need to get up to speed with the code, since its the first time I'll try something like this.
For now I hope you are using the https://github.com/marctdt/Bitwig_MaschineJam since it provides loads of functionality !

**Comment by cyanit** [comment]
I use some [script from the NI community forum](https://www.native-instruments.com/forum/threads/anyone-scripting-maschine-jam-for-bitwig.335637/), and now I checked there's even a nice update! Awesome

**Comment by MINDoSOFT** [comment]
I have started working on the mapping,
you can see my branch and progress here
https://github.com/MINDoSOFT/DrivenByMoss/tree/MaschineJAM

**Comment by MINDoSOFT** [comment]
Hello Jürgen !

I am trying to implement the BrowseMode for the Jam, and I would like some help. 

First of all what I'm trying to achieve is using the Directional-Pad (which has Up Down Left Right buttons) which send midi cc 40, 41, 42, 43 respectively, to navigate previousItem, nextItem, previousPage, nextPage.

Tried overriding the onButton function but with no luck. It doesn't seem to be called at all.
`public void onButton(int row, int index, ButtonEvent event) {`


On a different matter I have implemented the metronome button. Which basically is a combination of buttons. 
You need to keep pressing the shift button (which sends sysex data) and then press the Left Arrow button. Can you take a look at my commit and let me know if I can improve this code ?
https://github.com/MINDoSOFT/DrivenByMoss/commit/86e7cc9c977024dc95b9c624c09d149fc90ac056

Thanks !

**Comment by git-moss** [comment]
Midi mappings to commands happens in the *Setup classes. Look at the registerTrigger method.
Sorry, I do not have the time to get involved in this.

**Comment by MINDoSOFT** [comment]
With the latest version [DrivenByMoss 12.2.1](http://www.mossgrabers.de/Software/Bitwig/Bitwig.html) there is [Maschine JAM support](https://www.youtube.com/watch?v=aX0c_gVSwEk&list=PLwbNMIDrNMJuq0fn_Tfb4GLWXjrBBjSLA) !

Thank you very much Jürgen for your awesome work !

**Comment by git-moss** [comment]
You are welcome! :-)
