### ISSUE TITLE
OSC Messages: Beat position inside clip + clip loop start & length...

### ISSUE THREAD

**Issue by j28** [git-moss/DrivenByMoss#146]
Hi,

I am interested in making a step sequencer as a custom module inside Open Stage Control. In order for the sequencer to work I need the beat position inside a clip to be sent to Open Stage Control.

Something like /track/{1-8}/clip/{1-8}/beat which continuously returns the current beat position (ex. 1.2.1.00) for the clip would work.

Other necessesary parts would be /track/{1-8}/clip/{1-8}/loop/length (ex. 1.0.0.00) and /track/{1-8}/clip/{1-8}/loop/start (ex. 1.1.1.00).

Is it easy to add this functionality?

**Comment by git-moss** [comment]
You could make it work for MIDI clips. For audio this information is currently not accessible via the Bitwig API.
I thought about sending the MIDI note clip information but decided against it since the OSC message interface would be quite complicated and you would need to do some processing at the client side, which is not possible with most clients anyway.
If you want to have a go at it yourself, see my coding tutorial on Youtube about OSC.

**Comment by j28** [comment]
I see. I will watch the coding tutorial. Thanks.
