### ISSUE TITLE
Launchpad Mini mk3: No access to last row of clips when Stop/Solo/Mute/Record mode is enabled in the bottom row

### ISSUE THREAD

**Issue by anthroid** [git-moss/DrivenByMoss#174]
To reproduce (Bitwig 3.1.3, macOS 10.14.6):

1. Create a session with at least (8) occupied clip rows.
2. Switch to Session layout on the Launchpad Mini mk3 and press [Down] to scroll to the bottom of the session (all clips are displayed and accessible).
3. Press [User] and select [Stop Clip] to set the mode of the bottom row.
4. It is now impossible to access the last row of clips (unable to scroll down another row, [Stop Clip] buttons are overlaying the last row).

Workaround: This can be overcome by adding an extra row of empty clips to the session.

**Comment by git-moss** [comment]
I see what you mean. The problem is that I cannot switch between pages with 8 or 7 clip rows, so I cannot change this.

As a better workaround, I suggest to keep the Stop Clip button pressed, select the track to stop and then release the button. This will automatically hide the Clip Stop row. Also works with other modes.
