### ISSUE TITLE
Delete clip in Novation Launchkey Mini Mk3

### ISSUE THREAD

**Issue by TatriX** [git-moss/DrivenByMoss#249]
Hi! Is it possible to delete or clear somehow a recorded clip with Novation Launchkey Mini Mk3?

**Comment by git-moss** [comment]
Sorry, no. The number of buttons is a bit limited on this device.

**Comment by pieterdd** [comment]
Does the Launchkey hardware support long press events? From a UX perspective, assigning a long press action to a clip launching pad could be an interesting solution for two reasons:

- It adds a secondary function to a button that already has a primary function without having to switch modes
- To minimize the risk of accidentally performing a destructive action, such an action should be a bit harder to perform accidentally than regular actions. Long press is a way to achieve that.

If it's not possible or too complex, fair enough. I appreciate the work you've done making MIDI controllers usable in a bigger range of DAWs regardless!

**Comment by git-moss** [comment]
Long pressing a pad is already used to only select the clip without starting it.

**Comment by pieterdd** [comment]
Sorry, I wasn't aware. Would you be open to a new MIDI controller setting 'Behaviour on long pad press' where I can override the default action to 'Delete clip'?

**Comment by git-moss** [comment]
I don't think so because this goes in the direction of "configure each and every button" :-)

**Comment by pieterdd** [comment]
Fair enough, having more options increases technical complexity. I suggested it because I don't want to break anyone's workflow, but personally I don't have any use for the current action. So from my point of view, I wouldn't mind the clip selection feature being replaced with a clip deletion feature.

Meanwhile I found out that I can also press the Delete key on my regular keyboard, which seems to be an acceptable workaround. I think that'll do. Thanks again for all the work you did making this controller compatible with Bitwig, Jürgen!
