### ISSUE TITLE
Issue switching banks from APC40

### ISSUE THREAD

**Issue by skysplitterink** [git-moss/DrivenByMoss#28]
Wondering if anyone else is experiencing this. I have 9 tracks open,when I try to switch from track 8-9 the clip bank moves from 1-8 to 2-9 but instead of the track selection jumping to track 9 it jumps back to track 9 and I have to scroll all the way through the new bank. This has only happened since 2.2 I believe.

Any help would be amazing. Thank You.

**Comment by unity2k** [comment]
This was normal behavior I assumed due to some limitation or other. The way I would describe it is when I have 10 tracks setup in my DAW and I need to scroll over to track 9. As I pass track 8 the cursor jumps back to track 2 and I have to tab forward again until I reach track 9. A bit of inconvenience, but I've been living with it.

**Comment by git-moss** [comment]
That is a new behaviour which got introduced (I think) in v2. I also agree it should be changed back to the previous behaviour. I documented it here:
https://github.com/teotigraphix/Framework4Bitwig/issues/202

**Comment by skysplitterink** [comment]
Thank you 

    On Sunday, December 10, 2017 11:08 AM, Jürgen Moßgraber <notifications@github.com> wrote:
 

 That is a new behaviour which got introduced (I think) in v2. I also agree it should be changed back to the previous behaviour. I documented it here:
teotigraphix/Framework4Bitwig#202—
