### ISSUE TITLE
Unresponsive push when audio clip is selected in note mode

### ISSUE THREAD

**Issue by matthieu-mastio** [git-moss/DrivenByMoss#324]
Bitwig 4.3.8
DrivenByMoss-18.0.0-Bitwig
Windows 7
Push1

The Push1 becomes  unresponsive  whenever an audio track is selected and the push is in note mode .

[Here](https://drive.google.com/file/d/1ZWKdTINpy_X8N_WaMPJG8cH2-k2bIe9A/view?usp=sharing) is a video showing the problem (the recmel track is an audio track).

**Comment by git-moss** [comment]
I cannot replicate that. Any other hints what might be special about the Audio track?

**Comment by banermatt** [comment]
I am afraid there is nothing special about the track. I tried with a brand new track, with all the sends to zero, and even disabling all audio input, and the bug is persisting. I am not sure what would be the correct behavior in this situation. If I understand correctly from the documentation, it should be possible to use the pads to select the length of the selected audio clip right?

**Comment by git-moss** [comment]
Yes, that's the case but you need to switch to the "Tools -> CLIP" view. Will change that this will be automatically the case in the future.

**Comment by banermatt** [comment]
Hi Moss,

So I think I have finally found how to reproduce the problem.
The thing is I had the script configured to use drum layout by default. With this setting, if you are in note mode and select an audio track it will freeze the push for a while.

**Comment by git-moss** [comment]
I am sorry but I cannot reproduce that.
