### ISSUE TITLE
DrivenByMoss4Reaper on RaspberryPi

### ISSUE THREAD

**Issue by ezemtsov** [git-moss/DrivenByMoss#338]
Hi! Thanks a lot for your effort!

I'm using Reaper on Raspberry Pi and have Novation Launchpad Mini Mk3.
Is there any chance to make a build for DrivenByMoss4Reaper for aarch64 to enable it on Raspberry?

I'm happy to help with the build process, but didn't find source code publicly.

**Comment by git-moss** [comment]
I was thinking about it some time ago but at the time PIs were hard to get.
It is already a nightmare to keep up with 3 OSs, maybe if I feel pretty bored one day :-)

Regarding the code: I did intentionally not publish the Reaper glue code because it is quite difficult and I don't have the time to support this.
