### ISSUE TITLE
Feature requests for FaderFox EC4

### ISSUE THREAD

**Issue by madskjeldgaard** [git-moss/DrivenByMoss#379]
Hi ! 

First of all, thanks so much for the incredible EC4 script. It is mindblowingly nice, a true pleasure to use and I appreciate it so much!!

I have two small feature requests:
1. Add a visual cue to the small screen when changing between modes with knob button 14. The screen could briefly say "Mode: Track mode" etc. It would be a nice help to me at least.
2. Add the possibility to choose next/previous device in the user configurable actions, like you can now choose previous/next track for example. I really love these!!

Again, thanks so much, this is just fantastic

**Comment by madskjeldgaard** [comment]
and feel free to close if none of this is relevant / possible

**Comment by madskjeldgaard** [comment]
and feel free to close if none of this is relevant / possible

**Comment by git-moss** [comment]
1) This is sadly not possible since I have to use a weird hack to show the parameters on the display. Since the knobs are not touch sensitive, I do not know when the user changes a parameter. Therefore, I simply show all changes in the display as they appear in Bitwig (e.g. change the volume of a track to see what I mean). When changing modes the parameters do update and do directly overwrite the mode info.

2) You can already select devices with Shift+Buttons 5-12.
